services:
  UbuntuOne:
    image: ubuntu:latest
    container_name: UbuntuOne
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    hostname: UbuntuOne
    ports:
      - "8081:80"
    command: bash -c "
      apt-get update &&
      apt-get install -y openssh-server &&
      echo 'root:1234' | chpasswd &&
      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
      service ssh start &&
      tail -f /dev/null"
    restart: always
    networks:
      ubuntu_net:
        ipv4_address: 172.28.0.2
  UbuntuTwo:
    image: ubuntu:latest
    container_name: UbuntuTwo
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    hostname: UbuntuTwo
    ports:
      - "8082:80"
    command: bash -c "
      apt-get update &&
      apt-get install -y openssh-server &&
      echo 'root:1234' | chpasswd &&
      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
      service ssh start &&
      tail -f /dev/null"
    restart: always
    networks:
      ubuntu_net:
        ipv4_address: 172.28.0.3
  UbuntuThree:
    image: ubuntu:latest
    container_name: UbuntuThree
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    hostname: UbuntuThree
    ports:
      - "8083:80"
    command: bash -c "
      apt-get update &&
      apt-get install -y openssh-server &&
      echo 'root:1234' | chpasswd &&
      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
      service ssh start &&
      tail -f /dev/null"
    restart: always
    networks:
      ubuntu_net:
        ipv4_address: 172.28.0.4
  UbuntuFour:
    image: ubuntu:latest
    container_name: UbuntuFour
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    hostname: UbuntuFour
    ports:
      - "8084:80"
    command: bash -c "
      apt-get update &&
      apt-get install -y openssh-server &&
      echo 'root:1234' | chpasswd &&
      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
      service ssh start &&
      tail -f /dev/null"
    restart: always
    networks:
      ubuntu_net:
        ipv4_address: 172.28.0.5

networks:
  ubuntu_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/27
