---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    ansible.builtin.apt:
      update_cache: yes

  - name: stop nginx service
    ansible.builtin.service:
      name: nginx
      state: stopped

  - name: remove nginx package
    ansible.builtin.apt:
      name: nginx
      state: absent
