---
- name: SSH-Key deployment on new containers
  hosts: all
  gather_facts: no
  vars:
    ansible_user: root
    ansible_ssh_pass: "1234"
    ansible_connection: ssh
  tasks:
    - name: Copy public key to host
      ansible.builtin.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"

---
- name : Stop and remove nginx
  hosts: all
  become: true
  tasks:
  - name: stop nginx service
    ansible.builtin.service:
      name: nginx
      state: stopped

  - name: remove nginx package
    ansible.builtin.apt:
      name: nginx
      state: absent
      update_cache: yes
