---
- name: SSH-Key deployment on new containers
  hosts: all
  vars:
    ansible_user: root
    ansible_ssh_pass: "1234"
    ansible_connection: ssh
  tasks:
    - name: Copy public key to host
      ansible.builtin.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"

- name: Install all Updates
  hosts: all
  become: true
  tasks:
    - name: update repo cache (CentOS)
      tags: always
      ansible.builtin.dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"
    - name: update repo cache (Ubuntu)
      tags: always
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers